import "./globals.css";

import Nav from "./(components)/Nav";

export const metadata = {
	title: "UA Next Auth App",
	description: "Generated by UA",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className=' bg-gray-100'>
				<Nav />
				<div className=' m-2'>{children}</div>
			</body>
		</html>
	);
}
